// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"mi/internal/app"
	"mi/internal/app/api"
	"mi/internal/app/repo"
	"mi/internal/app/router"
	"mi/internal/app/service"
)

// Injectors from wire.go:

func initApp() (*app.App, func(), error) {
	userRepo := &repo.UserRepo{}
	userService := &service.UserService{
		UserRepo: userRepo,
	}
	userAPI := &api.UserAPI{
		UserSrv: userService,
	}
	routerRouter := &router.Router{
		UserAPI: userAPI,
	}
	engine := app.InitEngine(routerRouter)
	appApp := newApp(engine)
	return appApp, func() {
	}, nil
}
