jwt:
  signing-key: 'qmPlus'
  expires-time: 604800
  buffer-time: 86400
  issuer: 'qmPlus'

mysql:
  host: '39.108.235.46'
  port: 3306
  db-name: 'deephash'
  username: 'staples'
  password: 'staples'
  parameters: 'charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true'
  log-mode: ""
  log-zap: false

system:
  env: 'public'
  addr: "0.0.0.0"
  port: 8888
  db-type: 'mysql'
  is-debug: false
  max-life-time: 7200
  max-open-conns: 150
  max-idle-conns: 50
  table-prefix: 'go_mi_'
  enable-auto-migrate: true
  is-print-config: true

zap:
  level: 'info'
  prefix: 'hash-deep'
  format: 'console'
  director: 'log'
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  max-age: 30 # 默认日志留存默认以天为单位
  show-line: true
  log-in-console: true

redis:
  db: 0
  addr: '101.132.127.139:6379'
  password: 'hashdeep'

casbin:
  path: ''